### ISSUE TITLE
[UI] Sign up/ Login 

### ISSUE THREAD

**Issue by hongdtb41** [aesirxio/content-app#1]
https://www.figma.com/proto/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=7729%3A44089&scaling=min-zoom&page-id=7729%3A44088

**Comment by huynhngocgiau** [comment]
Done
![image](https://user-images.githubusercontent.com/79819354/216005022-03a5fe14-2738-4957-944f-052338a4ee53.png)
