### ISSUE TITLE
[UI] Items-Darkmode 

### ISSUE THREAD

**Issue by hongdtb41** [aesirxio/content-app#16]
https://www.figma.com/proto/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=7729%3A44226&scaling=min-zoom&page-id=7729%3A44088

**Comment by huynhngocgiau** [comment]
active item: #3B7AB5
![active](https://user-images.githubusercontent.com/79819354/215986664-2340dc55-c55f-437e-b0a9-50c9c1b8c303.png)
DAM
![Untitled](https://user-images.githubusercontent.com/79819354/216001431-dcda4ae9-3147-4261-9e30-8131bb547451.png)
![Untitled1](https://user-images.githubusercontent.com/79819354/216001441-1dcd8efd-1934-4800-b882-f35196a7d12c.png)
