### ISSUE TITLE
[UI] Categories 

### ISSUE THREAD

**Issue by hongdtb41** [aesirxio/content-app#6]
https://www.figma.com/proto/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=7729%3A45277&scaling=min-zoom&page-id=7729%3A44088

**Comment by huynhngocgiau** [comment]
Work
![image](https://user-images.githubusercontent.com/79819354/216259912-973c4d4a-ada7-485c-a2ac-d4fdd62cb748.png)
